### ISSUE TITLE
clear not working?

### ISSUE THREAD

**Issue by Lokua** [adamrenklint/dilla#21]
First of all thank you for this awesome lib. Great API and perfect name! 

Out of nowhere I'm having an issue with `clear`. In the following example, pressing play the first time adds a step handler and 1-4 is printed in order on the screen. Pressing stop will call `dilla.stop` and `dilla.clear`, but the events aren't actually removed, and seem to conflict with newer calls to `dilla.set`. Notice that each time you click play/pause, the numbers on screen get all screwy, and the `dilla._events.step` array just keeps growing (you can see some output in the console).

``` js
import Dilla from 'dilla'

const dilla = new Dilla(new AudioContext())
const channel = 'donuts'

const button = document.createElement('button')
const div = document.createElement('div')
button.textContent = 'play'
document.body.appendChild(button)
document.body.appendChild(div)

let isPlaying = false
let activeStep = -1

button.addEventListener('click', () => {
  (isPlaying = !isPlaying) ? play() : stop()
  button.textContent = isPlaying ? 'stop' : 'play'
})

function play() {
  dilla.set(channel, [['*.*.01']])

  // callback has to be named so I can find in monkey patch in stop fn below
  dilla.on('step', function stepHandler(step) {
    if (step.id !== channel || step.event !== 'start') {
      return
    }
    div.textContent = (++activeStep % 4) + 1
  })

  dilla.start()
}

function stop() {
  dilla.stop()
  dilla.clear(channel)

  console.group('after stop and clear:')
  console.log('dilla:', dilla)
  console.log('dilla._events:', dilla._events)
  console.log('dilla.listeners(\'step\'):', dilla.listeners('step'))
  console.groupEnd()

  // this is my ugly workaround at the moment
  // ---
  // if (typeof dilla._events.step === 'function' &&
  //     dilla._events.step.name === 'stepHandler') {
  //
  //   delete dilla._events.step
  //
  // } if (Array.isArray(dilla._events.step)) {
  //
  //   dilla._events.step = dilla._events.step.filter(handler => {
  //     return handler && handler.name !== 'stepHandler'
  //   })
  // }
}
```

Haven't looked at the source much so I'm probably debugging the wrong things, or just using it wrong totally ha. I'd be happy to post this to a repo as a runnable project if that makes it easier to run, btw.

**Comment by Lokua** [comment]
Ah - error on my part. What I needed was 

``` js
function stepHandler(step) {
  // do stuff
}

function play() {
  dilla.set(channel, [['*.*.01']])
  dilla.on('step', stepHandler)
  dilla.start()
}

function stop() {
  dilla.stop()

  // just needed this...
  dilla.removeListener('step', stepHandler)
  dilla.clear(channel)
}
```

Thanks again for the rawsomeness!

**Comment by adamrenklint** [comment]
Hey, good to hear you like the library, and thanks for the well-structured issue!
Was just typing the same thing :)

Depending on what you're building, you might wanna check out [Bap](https://github.com/adamrenklint/bap), a higher level abstraction over Dilla with MPC drum machine/sampler semantics.

✊
