### ISSUE TITLE
Changing beats per bar leads to confusion in the order of the steps

### ISSUE THREAD

**Issue by matstc** [adamrenklint/dilla#23]
I am using dilla to play a song at 4 beats per bar, then to play another song at 3 beats per bar.

The second song does not sound right: the steps do not come in the right order.

I believe this is linked to `getClockPositionFromPosition` being memoized even though it uses the instance variable `_beatsPerBar`. Changing the beats per bar won't invalidate the memoization.

Removing the call to `memoize` for that function fixed it.

How should this be fixed properly? Should `getClockPositionFromPosition` accept `beatsPerBar` as a parameter? I'm happy to submit a PR if you can guide me through the proper fix.

**Comment by adamrenklint** [comment]
Hey,
yeah, that seems to be exactly the problem, since `dilla. getClockPositionFromPosition` has a reference to `this._beatsPerBar` inside it. I'd love to see a PR with the fix proposed fix from you 👍
